# Generated by Django 6.0.5 on 2026-05-14 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('proyecto', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('codigo', 'Código'), ('diseno', 'Diseño'), ('documentacion', 'Documentación'), ('prueba', 'Prueba'), ('presentacion', 'Presentación'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('archivo_url', models.URLField(blank=True, default='', max_length=500)),
                ('archivo_nombre_original', models.CharField(blank=True, default='', max_length=255)),
                ('archivo_tipo', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('png', 'PNG'), ('jpeg', 'JPEG')], default='', max_length=10)),
                ('archivo_tamano', models.PositiveIntegerField(default=0, help_text='Tamaño en bytes')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidencia de Proyecto',
                'verbose_name_plural': 'Evidencias de Proyecto',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
